In [10]:
import numpy as np
import pandas as pd

X_train = pd.read_csv("C:/Users/Fernando/Desktop/Proyecto_Final_ML/data/X_train_3", index_col=0)
X_test = pd.read_csv("C:/Users/Fernando/Desktop/Proyecto_Final_ML/data/X_test_3", index_col=0)

features_columns = X_train.columns

y_train = pd.read_csv("C:/Users/Fernando/Desktop/Proyecto_Final_ML/data/y_train", index_col=0)
y_test = pd.read_csv("C:/Users/Fernando/Desktop/Proyecto_Final_ML/data/y_test", index_col=0)
y_train = np.ravel(y_train)
y_test = np.ravel(y_test)

In [11]:
X_train

,subproduct_class0_enc,Date received_day_of_month,Date received_day_week,Date received_weekend,Date sent to company_day_of_month,Date sent to company_day_week,Date sent to company_weekend,Product_Bank account or service,Product_Consumer loan,Product_Credit card,...,embedding_21,embedding_22,embedding_23,embedding_24,Company_type_Bank,Company_type_Bureau,Company_type_Collector,Company_type_Fintech,Company_type_Lender,Company_type_Other
0,0.898418,12,3,0,12,3,0,0,0,0,...,-0.426768,0.088779,1.374827,0.081172,0,0,0,0,1,0
1,0.927206,6,1,0,6,1,0,0,0,0,...,0.360980,0.603396,1.252212,-0.188674,0,0,0,0,1,0
2,0.927206,15,3,0,15,3,0,0,0,0,...,-0.426768,0.088779,1.374827,0.081172,0,0,0,0,1,0
3,0.912154,20,4,0,23,0,0,1,0,0,...,0.865649,-0.026394,0.262758,0.539379,1,0,0,0,0,0
4,0.725821,13,1,0,13,1,0,0,0,1,...,0.158699,0.262165,0.394589,0.406649,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16030,0.725821,4,2,0,9,0,0,0,0,0,...,-0.393521,1.199555,0.735366,1.160193,0,1,0,0,0,0
16031,0.725821,9,0,0,9,0,0,0,0,0,...,1.100750,-0.304429,0.038844,0.722807,0,0,1,0,0,0
16032,0.725821,14,5,1,14,5,1,0,0,0,...,-0.393521,1.199555,0.735366,1.160193,0,1,0,0,0,0
16033,0.725821,11,2,0,18,2,0,0,0,0,...,-0.393521,1.199555,0.735366,1.160193,0,1,0,0,0,0
16034,0.768155,31,5,1,31,5,1,0,0,0,...,0.208299,-0.446910,0.579503,1.253139,0,0,1,0,0,0

In [12]:
# Nos quedamos con las primeras columnas más importantes según el random forest del notebook ensemble

X_train = X_train[["Date received_day_of_month", "Date sent to company_day_of_month", 
"Date received_day_week","Date sent to company_day_week"]]

X_test = X_test[["Date received_day_of_month", "Date sent to company_day_of_month", 
"Date received_day_week","Date sent to company_day_week"]]


features_columns = X_train.columns

In [13]:
## Normalization
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
X_train = std_scaler.fit_transform(X_train)
X_test = std_scaler.transform(X_test)

In [17]:
### XGBOOST

import xgboost
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import classification_report

xgb_clas = xgboost.XGBClassifier(objective="binary:logistic", n_estimators=100, 
                                 learning_rate = 1 , random_state=42)

xgb_clas.fit(X_train, y_train)
y_pred = xgb_clas.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.29      0.01      0.01       815
           1       0.80      1.00      0.89      3194

    accuracy                           0.79      4009
   macro avg       0.54      0.50      0.45      4009
weighted avg       0.69      0.79      0.71      4009